import { Project } from './types';

/**
 * ─────────────────────────────────────────────────────────────
 *  PROJECT CATALOG — the only file you need to touch to
 *  add, edit, or remove a project. Every page (home carousel,
 *  catalog grid, detail page) reads from this array.
 *
 *  slug   → used in the URL: /projects/<slug>
 *  tier   → 'Tier 1' (flagship / featured) or 'Tier 2' (standard)
 *  domain → must match one of the Domain filters
 * ─────────────────────────────────────────────────────────────
 */
export const projects: Project[] = [
  // TIER 1 - HIGHEST DEMAND
  {
    slug: 'fake-news-detection',
    title: 'Fake News Detection using BERT + LSTM',
    tier: 'Tier 1',
    domain: 'NLP',
    techStack: ['Python', 'HuggingFace', 'Flask', 'BERT', 'LSTM'],
    shortDesc: 'Deep learning model that detects fake news with 94%+ accuracy using transformer embeddings.',
    longDesc: 'Combines BERT text embeddings with LSTM sequence modeling to classify news articles as real or fake. Includes a Flask REST API and a web dashboard for batch processing, with feature importance analysis.',
    features: [
      'BERT + LSTM ensemble architecture',
      '94%+ accuracy on benchmark datasets',
      'Flask REST API with Swagger docs',
      'Web dashboard for batch prediction',
      'Feature attribution visualization',
    ],
    demoUrl: 'https://example.com/demo/fake-news',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/fake-news.svg',
    ieeeBase: 'IEEE Access 2024 — Fake News Detection with Transformers',
    pricing: [
      { name: 'Source Only', price: 2499, features: ['Full source code', 'Setup guide', 'Dataset links'] },
      {
        name: 'Full Kit',
        price: 4999,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 7499,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report', '1 custom module'],
      },
    ],
  },
  {
    slug: 'resume-screening-automation',
    title: 'Resume Screening Automation with NLP',
    tier: 'Tier 1',
    domain: 'NLP',
    techStack: ['Python', 'spaCy', 'Flask', 'scikit-learn'],
    shortDesc: 'Automated resume parsing and ranking engine for HR using NLP-based candidate profiling.',
    longDesc: 'Uses spaCy for named entity recognition to extract skills, experience, and education from resumes. Ranks candidates against job requirements using TF-IDF similarity scoring.',
    features: [
      'Automated resume parsing (PDF/DOCX)',
      'Skills and experience extraction using NER',
      'TF-IDF based ranking against job description',
      'Candidate profile standardization',
      'Batch processing support',
    ],
    demoUrl: 'https://example.com/demo/resume-screening',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/resume-screening.svg',
    ieeeBase: 'IEEE ICCSC 2023 — NLP for HR Analytics',
    pricing: [
      { name: 'Source Only', price: 2299, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 4799,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 7299,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report', '1 custom module'],
      },
    ],
  },
  {
    slug: 'deepfake-image-detection',
    title: 'Deepfake Image Detection using CNN',
    tier: 'Tier 1',
    domain: 'Computer Vision',
    techStack: ['Python', 'TensorFlow', 'OpenCV', 'Keras'],
    shortDesc: 'Detects manipulated and deepfake images using convolutional neural networks with 96% accuracy.',
    longDesc: 'A CNN classifier trained on real and synthetic manipulated images. Uses frequency domain analysis and deep learning to detect subtle artifacts in deepfakes.',
    features: [
      'CNN + ResNet50 transfer learning',
      '96% detection accuracy',
      'Frequency domain artifact detection',
      'Real-time inference',
      'Confidence scoring with heatmaps',
    ],
    demoUrl: 'https://example.com/demo/deepfake-detection',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/deepfake-detection.svg',
    ieeeBase: 'IEEE CVPR 2024 — Synthetic Media Detection',
    pricing: [
      { name: 'Source Only', price: 2599, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 5099,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 7599,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report', '1 custom module'],
      },
    ],
  },
  {
    slug: 'student-performance-prediction',
    title: 'Student Performance Prediction System',
    tier: 'Tier 1',
    domain: 'Medical AI',
    techStack: ['Python', 'Scikit-learn', 'Streamlit', 'XGBoost'],
    shortDesc: 'ML-based system predicting student academic performance and identifying at-risk learners.',
    longDesc: 'Regression and classification models trained on historical student data to predict final grades and categorize risk levels. Includes an interpretable dashboard for educators.',
    features: [
      'XGBoost + Random Forest ensemble',
      'Feature importance analysis for educators',
      'Early warning system for at-risk students',
      'Streamlit interactive dashboard',
      'Personalized intervention recommendations',
    ],
    demoUrl: 'https://example.com/demo/student-perf',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/student-perf.svg',
    ieeeBase: 'IEEE EDULEARN 2023 — ML for EdTech Analytics',
    pricing: [
      { name: 'Source Only', price: 1899, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 3999,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 6299,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'document-summarizer',
    title: 'Transformer-Based Document Summarizer',
    tier: 'Tier 1',
    domain: 'GenAI',
    techStack: ['Python', 'HuggingFace', 'Streamlit', 'Transformers'],
    shortDesc: 'Abstractive text summarization using fine-tuned transformer models for multi-lingual documents.',
    longDesc: 'Fine-tuned BART and T5 models for abstractive summarization. Supports multi-language documents and extractive fallback for edge cases.',
    features: [
      'Fine-tuned BART/T5 models',
      'Abstractive & extractive modes',
      'Multi-language support',
      'Streamlit web interface',
      'Batch document processing',
    ],
    demoUrl: 'https://example.com/demo/doc-summarizer',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/doc-summarizer.svg',
    ieeeBase: 'IEEE NLP 2024 — Abstractive Summarization',
    pricing: [
      { name: 'Source Only', price: 2299, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 4599,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 6999,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'brain-tumor-detection',
    title: 'Brain Tumor Detection from MRI Scans',
    tier: 'Tier 1',
    domain: 'Medical AI',
    techStack: ['Python', 'TensorFlow', 'OpenCV', 'Grad-CAM'],
    shortDesc: 'CNN model for brain tumor classification from MRI with explainable AI using Grad-CAM heatmaps.',
    longDesc: 'Classifies MRI scans into tumor types (glioma, meningioma, pituitary) with 99% accuracy using U-Net and VGG16. Provides explainability through Grad-CAM visualization.',
    features: [
      'U-Net + VGG16 architecture, 99% accuracy',
      'Grad-CAM explainability heatmaps',
      'Tumor localization and segmentation',
      'Django admin dashboard',
      'DICOM file support',
    ],
    demoUrl: 'https://example.com/demo/brain-tumor',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/brain-tumor.svg',
    ieeeBase: 'IEEE TMI 2024 — Deep Learning for Medical Imaging',
    pricing: [
      { name: 'Source Only', price: 2799, features: ['Full source code', 'Setup guide', 'Dataset'] },
      {
        name: 'Full Kit',
        price: 5299,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 7999,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report', '1 custom module'],
      },
    ],
  },
  {
    slug: 'diabetes-prediction-web-app',
    title: 'Diabetes Risk Prediction Web Application',
    tier: 'Tier 1',
    domain: 'Medical AI',
    techStack: ['Python', 'XGBoost', 'Flask', 'React'],
    shortDesc: 'Real-time diabetes risk prediction model with personalized health insights and visualizations.',
    longDesc: 'XGBoost-based risk predictor trained on PIMA Indian Diabetes dataset. Provides feature importance, SHAP explanations, and health recommendations.',
    features: [
      'XGBoost classifier, 95% AUC',
      'SHAP feature importance explanations',
      'Personalized health recommendations',
      'Risk stratification dashboard',
      'Historical tracking',
    ],
    demoUrl: 'https://example.com/demo/diabetes-prediction',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/diabetes-prediction.svg',
    ieeeBase: 'IEEE Healthtech 2023 — ML for Disease Prediction',
    pricing: [
      { name: 'Source Only', price: 1799, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 3599,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 5599,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'driver-drowsiness-detection',
    title: 'Driver Drowsiness Detection System',
    tier: 'Tier 1',
    domain: 'Computer Vision',
    techStack: ['Python', 'OpenCV', 'dlib', 'Flask'],
    shortDesc: 'Real-time driver fatigue detection using eye-aspect-ratio (EAR) method with alarm system.',
    longDesc: 'Detects driver drowsiness using facial landmarks and eye aspect ratio. Triggers alerts when drowsiness is detected from webcam or vehicle camera feeds.',
    features: [
      'Real-time facial landmark detection',
      'Eye-aspect-ratio (EAR) algorithm',
      'Alarm system with notifications',
      'Dashboard with drowsiness history',
      'Works on embedded systems',
    ],
    demoUrl: 'https://example.com/demo/drowsiness-detection',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/drowsiness-detection.svg',
    ieeeBase: 'IEEE ITSC 2023 — Vision-based Driver Monitoring',
    pricing: [
      { name: 'Source Only', price: 1699, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 3399,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 5299,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'rag-document-qa-system',
    title: 'RAG-Based Document Q&A System',
    tier: 'Tier 1',
    domain: 'GenAI',
    techStack: ['LangChain', 'FAISS', 'OpenAI', 'React', 'FastAPI'],
    shortDesc: 'Retrieval-augmented generation system for intelligent document querying with context-aware answers.',
    longDesc: 'Combines document retrieval (FAISS vector search) with LLM generation for accurate, context-grounded Q&A. Handles multi-document queries and citation tracking.',
    features: [
      'FAISS vector store with semantic search',
      'RAG pipeline with GPT-4 integration',
      'Citation tracking and source attribution',
      'Multi-document context handling',
      'React + FastAPI full-stack app',
    ],
    demoUrl: 'https://example.com/demo/rag-qa',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/rag-qa.svg',
    ieeeBase: 'IEEE SIGIR 2024 — RAG for Enterprise QA',
    pricing: [
      { name: 'Source Only', price: 2699, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 5199,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 7999,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report', '1 custom module'],
      },
    ],
  },
  {
    slug: 'video-lecture-summarizer',
    title: 'Video Lecture Summarizer with Transcription',
    tier: 'Tier 1',
    domain: 'GenAI',
    techStack: ['Python', 'Whisper', 'GPT API', 'Streamlit'],
    shortDesc: 'Automatically transcribes and summarizes lecture videos into study notes.',
    longDesc: 'Combines OpenAI Whisper for speech-to-text with GPT for generating study notes, slides, and quiz questions from lecture videos.',
    features: [
      'OpenAI Whisper speech recognition',
      'LLM-based abstractive summarization',
      'Auto-generated study notes and Q&A',
      'Slide deck generation from transcript',
      'Multi-language support',
    ],
    demoUrl: 'https://example.com/demo/lecture-summarizer',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/lecture-summarizer.svg',
    ieeeBase: 'IEEE EDULEARN 2024 — AI for Educational Content',
    pricing: [
      { name: 'Source Only', price: 2399, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 4799,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 7299,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report', '1 custom module'],
      },
    ],
  },
  // TIER 2 - GOOD PROFIT
  {
    slug: 'ai-interview-question-generator',
    title: 'AI Interview Question Generator',
    tier: 'Tier 2',
    domain: 'GenAI',
    techStack: ['Python', 'GPT API', 'React', 'FastAPI'],
    shortDesc: 'Role-based interview question generation using LLMs with difficulty levels and skill mapping.',
    longDesc: 'Generates contextual interview questions for specific roles and skill levels using GPT. Includes sample answers and evaluation rubrics.',
    features: [
      'Role-specific question generation',
      'Difficulty level adjustment',
      'Sample answers with evaluation criteria',
      'Interview practice dashboard',
      'Performance analytics',
    ],
    demoUrl: 'https://example.com/demo/interview-gen',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/interview-gen.svg',
    ieeeBase: 'IEEE HCI 2024 — AI for Recruitment',
    pricing: [
      { name: 'Source Only', price: 1999, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 3799,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 5799,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'sentiment-analysis-dashboard',
    title: 'Sentiment Analysis Dashboard',
    tier: 'Tier 2',
    domain: 'NLP',
    techStack: ['Python', 'BERT', 'Flask', 'React'],
    shortDesc: 'Real-time social media sentiment analysis with trend visualization and topic modeling.',
    longDesc: 'Analyzes text sentiment using BERT and VADER. Tracks sentiment trends over time and identifies key topics driving sentiment shifts.',
    features: [
      'BERT fine-tuning for custom domains',
      'Real-time sentiment scoring',
      'Trend analysis and visualization',
      'Topic extraction using LDA',
      'Social media integration APIs',
    ],
    demoUrl: 'https://example.com/demo/sentiment-analysis',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/sentiment-analysis.svg',
    ieeeBase: 'IEEE SocialCom 2024 — Sentiment Analysis',
    pricing: [
      { name: 'Source Only', price: 1699, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 3299,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 5099,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'plagiarism-detection-system',
    title: 'Plagiarism Detection System',
    tier: 'Tier 2',
    domain: 'NLP',
    techStack: ['Python', 'TF-IDF', 'scikit-learn', 'Flask'],
    shortDesc: 'Academic plagiarism detection using TF-IDF cosine similarity and neural embeddings.',
    longDesc: 'Compares submitted documents against a corpus using multiple similarity metrics. Detects paraphrasing and reorganized content.',
    features: [
      'TF-IDF + cosine similarity',
      'Semantic similarity using embeddings',
      'Paraphrase detection',
      'Detailed similarity reports with highlights',
      'Batch processing capability',
    ],
    demoUrl: 'https://example.com/demo/plagiarism',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/plagiarism.svg',
    ieeeBase: 'IEEE EDULEARN 2023 — Academic Integrity',
    pricing: [
      { name: 'Source Only', price: 1499, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 2999,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 4599,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'skin-disease-detection',
    title: 'Skin Disease Classification System',
    tier: 'Tier 2',
    domain: 'Medical AI',
    techStack: ['Python', 'MobileNetV2', 'TensorFlow', 'Streamlit'],
    shortDesc: 'Dermatology image classification for skin disease diagnosis using MobileNetV2.',
    longDesc: 'Classifies skin lesions into benign and malignant categories. Optimized for mobile deployment with real-time camera capture.',
    features: [
      'MobileNetV2 transfer learning',
      '92% classification accuracy',
      'Real-time camera capture',
      'Confidence scores with clinical guidance',
      'Mobile-optimized deployment',
    ],
    demoUrl: 'https://example.com/demo/skin-disease',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/skin-disease.svg',
    ieeeBase: 'IEEE Healthtech 2023 — AI in Dermatology',
    pricing: [
      { name: 'Source Only', price: 1899, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 3599,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 5399,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'phishing-url-detection',
    title: 'Phishing URL Detection Chrome Extension',
    tier: 'Tier 2',
    domain: 'Cybersecurity',
    techStack: ['Python', 'scikit-learn', 'Flask', 'JavaScript'],
    shortDesc: 'ML-based URL classifier protecting users from phishing attacks in real-time.',
    longDesc: 'Classifies URLs as legitimate or phishing using feature engineering and ensemble ML models. Deployed as a browser extension.',
    features: [
      'Random Forest + XGBoost ensemble',
      '96% detection accuracy',
      'Real-time browser integration',
      'Lightweight extension (<500KB)',
      'Offline operation capability',
    ],
    demoUrl: 'https://example.com/demo/phishing-url',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/phishing-url.svg',
    ieeeBase: 'IEEE Cybersec 2024 — URL Classification',
    pricing: [
      { name: 'Source Only', price: 1299, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 2599,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 4099,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'job-portal-ai-matching',
    title: 'Job Portal with AI Matching Engine',
    tier: 'Tier 2',
    domain: 'Medical AI',
    techStack: ['React', 'Node.js', 'Python', 'NLP', 'MongoDB'],
    shortDesc: 'Full-stack job portal with intelligent resume-to-job matching using NLP.',
    longDesc: 'Matches job seekers with opportunities using semantic similarity between resumes and job descriptions. Includes employer and candidate dashboards.',
    features: [
      'Resume-to-job semantic matching',
      'Bidirectional search (jobs for users, users for jobs)',
      'Saved preferences and notifications',
      'Employer and candidate dashboards',
      'Application tracking system',
    ],
    demoUrl: 'https://example.com/demo/job-portal',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/job-portal.svg',
    ieeeBase: 'IEEE JobTech 2024 — AI Recruitment',
    pricing: [
      { name: 'Source Only', price: 2499, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 4999,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 7499,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report', '1 custom module'],
      },
    ],
  },
  {
    slug: 'ai-career-guidance-platform',
    title: 'AI Career Guidance Recommendation Platform',
    tier: 'Tier 2',
    domain: 'GenAI',
    techStack: ['React', 'FastAPI', 'GPT API', 'MongoDB'],
    shortDesc: 'Personalized career path recommendations using LLM and user profiling.',
    longDesc: 'Analyzes skills, interests, and market trends to provide tailored career guidance. Includes learning path suggestions and skill gap analysis.',
    features: [
      'LLM-powered career recommendations',
      'Personalized learning path generation',
      'Skill gap analysis',
      'Market trend integration',
      'Progress tracking and milestones',
    ],
    demoUrl: 'https://example.com/demo/career-guidance',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/career-guidance.svg',
    ieeeBase: 'IEEE EdTech 2024 — AI Career Planning',
    pricing: [
      { name: 'Source Only', price: 1999, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 3999,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 6299,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'text-to-sql-query-generator',
    title: 'Text-to-SQL Query Generator',
    tier: 'Tier 2',
    domain: 'GenAI',
    techStack: ['Python', 'GPT API', 'SQLite', 'React'],
    shortDesc: 'Converts natural language queries into SQL using LLMs with schema awareness.',
    longDesc: 'Uses few-shot prompting and schema context to generate accurate SQL from English questions. Includes query validation and explanation.',
    features: [
      'Natural language to SQL conversion',
      'Schema-aware generation',
      'Query validation before execution',
      'Explanation generation for queries',
      'Support for complex joins',
    ],
    demoUrl: 'https://example.com/demo/text-to-sql',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/text-to-sql.svg',
    ieeeBase: 'IEEE SIGMOD 2024 — Natural Language Interfaces',
    pricing: [
      { name: 'Source Only', price: 1699, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 3299,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 4999,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'ai-flashcard-generator',
    title: 'AI Flashcard Generator from Notes',
    tier: 'Tier 2',
    domain: 'GenAI',
    techStack: ['Python', 'PDF Parse', 'GPT API', 'React'],
    shortDesc: 'Automatically generates study flashcards from PDF notes and documents.',
    longDesc: 'Extracts key concepts from PDFs and generates flashcard Q&A pairs using LLMs. Supports spaced repetition learning.',
    features: [
      'PDF/Text document parsing',
      'LLM-powered Q&A generation',
      'Automatic categorization',
      'Spaced repetition scheduling',
      'Mobile-friendly flashcard interface',
    ],
    demoUrl: 'https://example.com/demo/flashcard-gen',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/flashcard-gen.svg',
    ieeeBase: 'IEEE EDULEARN 2024 — Learning Technology',
    pricing: [
      { name: 'Source Only', price: 1399, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 2799,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 4299,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
  {
    slug: 'social-media-influencer-fraud-detector',
    title: 'Social Media Influencer Fraud Detector',
    tier: 'Tier 2',
    domain: 'Cybersecurity',
    techStack: ['Python', 'Instagram API', 'ML', 'Streamlit'],
    shortDesc: 'Detects fake followers and engagement manipulation on social media profiles.',
    longDesc: 'Analyzes engagement patterns, follower demographics, and posting behavior to identify bot accounts and fake followers.',
    features: [
      'Engagement pattern analysis',
      'Bot detection using ML',
      'Follower authenticity scoring',
      'Influencer profile analysis',
      'Real-time monitoring dashboard',
    ],
    demoUrl: 'https://example.com/demo/influencer-fraud',
    demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/thumbnails/influencer-fraud.svg',
    ieeeBase: 'IEEE SocialCom 2024 — Fraud Detection',
    pricing: [
      { name: 'Source Only', price: 1799, features: ['Full source code', 'Setup guide'] },
      {
        name: 'Full Kit',
        price: 3399,
        highlighted: true,
        features: ['Full source code', 'IEEE report', 'PPT', 'Demo video', '2 support calls'],
      },
      {
        name: 'Full Kit + Priority Support',
        price: 5099,
        features: ['Everything in Full Kit', 'Unlimited support', 'Plagiarism report'],
      },
    ],
  },
];

export const getProjectBySlug = (slug: string) =>
  projects.find((p) => p.slug === slug);

export const domains = Array.from(new Set(projects.map((p) => p.domain)));
export const tiers = Array.from(new Set(projects.map((p) => p.tier)));
